class mitm_common {
    class common {
        class addToZeus {};
        class animDance {};
        class animDanceStart {};
        class animDanceEnd {};
        class animDance2;
        class animRelax {};
        class animRelaxEnd {};
        class animSquat {};
        class animSquatStart {};
        class animSquatEnd {};
        class clearMarkerCategory {};
        class createCategoryMarker {};
        class createTrigger {};
        class customChat {};
        class doAnimation {};
        class emptyContainer {};
        class fadeMarker {};
        class findBuildings {};
        class findMaxMoonDate {};
        class findRandomPos {};
        class getAdminID {};
        class getAverageDirection {};
        class getAveragePosition {};
        class getIslandConfigEntry {};
        class getMissionConfigEntry {};
        class getRoadDir {};
        class getSideColor {};
        class getSideName {};
        class getVectorAngle {};
        class handleDamageVehicle;
        class isCourier {};
        class nearestCoast {};
        class projectile {};
        class promptAdminResponse {};
        class stopAnimation {};
        class suppress {};
        class taskPatrol {};
        class teleport {};
        class temp3dMarker {};
    };
};
